apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ddareuwang
  namespace: default
spec:
  template:
    spec:
      containers:
      - image: gcr.io/multi-final-project/ddareuwang:v1.0.2
        env:
        - name: FLASK_APP
          value: "app.py"
        - name: FLASK_ENV
          value: "development"
        - name: FLASK_RUN_HOST
          value: "0.0.0.0"
        - name: FLASK_RUN_PORT
          value: "8080"
        ports:
        - containerPort: 8080
        command: ["flask", "run"]