services:
  ddareuwang:       # 컨테이너 이름(서비스명) : 내가 임의로 지정 가능
    build:
      context: .
      # dockerfile: Dockerfile.dev

    image:  ddareuwang:v1.0.2  # 이미지 이름: 이 경우에는 '베이스 이미지 이름:버전'으로 사용함
    container_name: ddareuwang-container
    ports:
      - "8080:8080"
    working_dir: /flask_server # 여기서 컨테이너 실행 시작
    volumes:
      - ./flask_server:/flask_server
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=8080
    restart: no # 실제 배포시에는  restart: unless-stopped
    command: flask run
